<a href="https://colab.research.google.com/github/Jeyakumar-M/Learnings/blob/main/DeepLearning/pytorch_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


## Introduction to Tensors
tensors - multi dimentional numerical objects
# Creating Tensors

In [ ]:
# we can create tensors using torch.tensor()
# single value is known as scaler
scalar = torch.tensor(5)
scalar

tensor(5)

In [ ]:
scalar.ndim

0

In [ ]:
# represents the normal integer value
scalar.item()

5

In [ ]:
# vector
vector = torch.tensor([2,3])
vector

tensor([2, 3])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
matrix = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
matrix.shape

torch.Size([3, 3])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[1]

tensor([4, 5, 6])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,0]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 0]]])

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR[0][0]

tensor([1, 2, 3])

In [ ]:
TENSOR1 = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],
                        [[2,3,4],[5,6,7],[8,9,0]]])
TENSOR1

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[2, 3, 4],
         [5, 6, 7],
         [8, 9, 0]]])

In [ ]:
TENSOR1.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR1.ndim

3

In [ ]:
TENSOR1[1][0][1]

tensor(3)

## Random Tensors

The thing why we need random tensors is many neural networks learns with tensors full of random numbers.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# to create a random tensor of size(3,3)
random_tensor = torch.rand(3,3)
random_tensor

tensor([[0.4332, 0.5881, 0.4528],
        [0.4887, 0.5225, 0.3095],
        [0.4706, 0.9388, 0.8648]])

In [ ]:
rand_tensor = torch.rand(5,5,5)
rand_tensor

tensor([[[0.0453, 0.2699, 0.9944, 0.4020, 0.2978],
         [0.6314, 0.9492, 0.1711, 0.8930, 0.4773],
         [0.7220, 0.0354, 0.5601, 0.7552, 0.0736],
         [0.3528, 0.9262, 0.5396, 0.9220, 0.0473],
         [0.9628, 0.3481, 0.7733, 0.0256, 0.3944]],

        [[0.5615, 0.0924, 0.7252, 0.7588, 0.6852],
         [0.6299, 0.9559, 0.2746, 0.5524, 0.1053],
         [0.2321, 0.7987, 0.2874, 0.8829, 0.2682],
         [0.6354, 0.8883, 0.1866, 0.4468, 0.5713],
         [0.7767, 0.0605, 0.2170, 0.6862, 0.9124]],

        [[0.1099, 0.3090, 0.6197, 0.9133, 0.7953],
         [0.3714, 0.6502, 0.9888, 0.2721, 0.9915],
         [0.2516, 0.2876, 0.3053, 0.7816, 0.2130],
         [0.4749, 0.3775, 0.2236, 0.3020, 0.5756],
         [0.8309, 0.6070, 0.1766, 0.5378, 0.3437]],

        [[0.6737, 0.9131, 0.4980, 0.8451, 0.4017],
         [0.4584, 0.8124, 0.6849, 0.6740, 0.0268],
         [0.5902, 0.5547, 0.0060, 0.2896, 0.5130],
         [0.2743, 0.8551, 0.8446, 0.3942, 0.2375],
         [0.3591, 0.1257,

In [ ]:
rand_tensor.shape

torch.Size([5, 5, 5])

In [ ]:
# to create a tensor which has similiar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channel(RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
random_image_size_tensor[:2]

tensor([[[0.7075, 0.0664, 0.2410],
         [0.1487, 0.6459, 0.2021],
         [0.0575, 0.5170, 0.9599],
         ...,
         [0.6228, 0.1344, 0.1231],
         [0.5356, 0.4020, 0.9970],
         [0.8234, 0.6750, 0.1802]],

        [[0.3350, 0.0207, 0.2667],
         [0.3804, 0.5202, 0.4795],
         [0.3642, 0.1032, 0.5504],
         ...,
         [0.7041, 0.7818, 0.7376],
         [0.7014, 0.4641, 0.0352],
         [0.6823, 0.4729, 0.3605]]])

### Zeros and Ones

In [ ]:
# to create a tensor with zeros
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# to create a tensor with ones
ones = torch.ones(4,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

## Create a range of tensors

In [ ]:
torch.range(5,20)

<ipython-input-34-e9c547590717>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(5,20)


tensor([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17., 18.,
        19., 20.])

In [ ]:
two_to_20 = torch.arange(2,20,4)

In [ ]:
# to create tensors like other tensors
zeros1 = torch.zeros_like(two_to_20)
zeros1

tensor([0, 0, 0, 0, 0])

In [ ]:
# default datatype of a tensor is float32

t1 = torch.tensor([1.0,2,3],
                  dtype=torch.float32,
                  device=None,
                  requires_grad=False)
t1.device, t1.dtype, t1.shape

(device(type='cpu'), torch.float32, torch.Size([3]))

#Tensor manipulations

In [ ]:
tensor1 = torch.tensor([1,2,3])
print("Tensor addition: ",tensor1+tensor1)
print("Tensor subtraction: ",tensor1-2)
print("Tensor Multiplication (element wise): ",tensor1*5)
print("Tensor Division: ",tensor1/2)
print("Matrix Multiplication: ",torch.matmul(tensor1,tensor1))

Tensor addition:  tensor([2, 4, 6])
Tensor subtraction:  tensor([-1,  0,  1])
Tensor Multiplication (element wise):  tensor([ 5, 10, 15])
Tensor Division:  tensor([0.5000, 1.0000, 1.5000])
Matrix Multiplication:  tensor(14)


In [ ]:
'''
  Main rule for matrix multiplications
  1. The inner imensions must be same
  2. The result matrix should be in the shape of outer dimensions
'''
torch.matmul(torch.rand(3,2),torch.rand(2,3)) # torch.mm() is same as torch.matmul()

tensor([[0.6439, 0.8702, 0.4666],
        [0.1958, 0.2518, 0.1460],
        [0.4177, 0.5543, 0.3059]])

In [ ]:
# To transpose a matrix we can use the .T operator
tensor1 = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor2 = torch.tensor([[6,7],
                        [8,9],
                        [10,11]])
print(f"Actual shape: tensor1: {tensor1.shape}\n {tensor1}\n, tensor2: {tensor2.shape}\n {tensor2}")
print(f"After Transpose: shape: {tensor2.T.shape}, matrix:\n {tensor2.T}")
torch.mm(tensor1,tensor2.T)

Actual shape: tensor1: torch.Size([3, 2])
 tensor([[1, 2],
        [3, 4],
        [5, 6]])
, tensor2: torch.Size([3, 2])
 tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])
After Transpose: shape: torch.Size([2, 3]), matrix:
 tensor([[ 6,  8, 10],
        [ 7,  9, 11]])


tensor([[ 20,  26,  32],
        [ 46,  60,  74],
        [ 72,  94, 116]])

# Tensor Aggregations

In [ ]:
x = torch.arange(0,100,9)
x

tensor([ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99])

In [ ]:
# find min and max
print("Max: ",torch.max(x),x.max())
print("Min: ",torch.min(x),x.min())

Max:  tensor(99) tensor(99)
Min:  tensor(0) tensor(0)


In [ ]:
# To find mean note: torch.mean() requires a tensor of float32 datatype so we have to convert the int64 tensor to float32 using the type convertor
print("dtype: ",x.dtype)
#print(x.mean())
print(x.type(torch.float32).mean())
print(torch.mean(x.type(torch.float32)))

dtype:  torch.int64
tensor(49.5000)
tensor(49.5000)


In [ ]:
# find sum
torch.sum(x), x.sum()

(tensor(594), tensor(594))

In [ ]:
# to find the min and max value index position we can use argmin() and argmax() functions
print(x.argmin())
print(x.argmax())

tensor(0)
tensor(11)


# reshaping, view, stack, squeeze, unsqueeze,

In [ ]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# reshaping - it will return a view(if the data is contiguous) or a copy( if the data is not contiguous - change in copy does not affect the original tensor)
x_reshape = x.reshape(2,5)
print("Actual: ",x_reshape)
x_reshape[0,4] = 1000
print("changed: ",x_reshape)
print("tensor also changed: ",x)

# changing in the actual tensor
x[2] = 2546
print("changed tensor: ",x)
print("x_reshape: ",x_reshape)

Actual:  tensor([[   0,    1,   22,    3, 1000],
        [   5,    6,    7,    8,    9]])
changed:  tensor([[   0,    1,   22,    3, 1000],
        [   5,    6,    7,    8,    9]])
tensor also changed:  tensor([   0,    1,   22,    3, 1000,    5,    6,    7,    8,    9])
changed tensor:  tensor([   0,    1, 2546,    3, 1000,    5,    6,    7,    8,    9])
x_reshape:  tensor([[   0,    1, 2546,    3, 1000],
        [   5,    6,    7,    8,    9]])


In [ ]:
# view - same as reshaping but it shares the same memory. it does not create a copy of the tensor
x_view = x.view(5,2)
print("view: ",x_view)
x_view[1,0] = 22
print("view changed: ", x_view)
print("original also changed: ",x)

view:  tensor([[   0,    1],
        [   2,    3],
        [1000,    5],
        [   6,    7],
        [   8,    9]])
view changed:  tensor([[   0,    1],
        [  22,    3],
        [1000,    5],
        [   6,    7],
        [   8,    9]])
original also changed:  tensor([   0,    1,   22,    3, 1000,    5,    6,    7,    8,    9])


In [ ]:
# Stack - combining tensors on top of each others. vstack and hstack
x_stack = torch.stack([x,x,x],dim=1)
x_stack

tensor([[   0,    0,    0],
        [   1,    1,    1],
        [2546, 2546, 2546],
        [   3,    3,    3],
        [1000, 1000, 1000],
        [   5,    5,    5],
        [   6,    6,    6],
        [   7,    7,    7],
        [   8,    8,    8],
        [   9,    9,    9]])

In [ ]:
x_stack = torch.stack([x,x,x],dim=0)
x_stack

tensor([[   0,    1, 2546,    3, 1000,    5,    6,    7,    8,    9],
        [   0,    1, 2546,    3, 1000,    5,    6,    7,    8,    9],
        [   0,    1, 2546,    3, 1000,    5,    6,    7,    8,    9]])

In [ ]:
# squeeze - remove all one dimensions from the tensor
y = torch.rand(2,1,2,1)
print(y)
print("shape of y: ",y.shape)

y_squeeze = y.squeeze()

print("After squeeze: ",y_squeeze)
print("new shape: ", y_squeeze.shape)

tensor([[[[0.2277],
          [0.6267]]],


        [[[0.7261],
          [0.1041]]]])
shape of y:  torch.Size([2, 1, 2, 1])
After squeeze:  tensor([[0.2277, 0.6267],
        [0.7261, 0.1041]])
new shape:  torch.Size([2, 2])


In [ ]:
# unsqueeze - adds one dimensions to the tensor
y_unsqueezed = y_squeeze.unsqueeze(dim=-1)
print(y_unsqueezed)
print("unsqueezed shape: ",y_unsqueezed.shape)

tensor([[[0.2277],
         [0.6267]],

        [[0.7261],
         [0.1041]]])
unsqueezed shape:  torch.Size([2, 2, 1])


In [ ]:
# permute
y_permute = y.permute(3,1,0,2)
print(y_permute)

tensor([[[[0.2277, 0.6267],
          [0.7261, 0.1041]]]])


## Indexing

In [5]:
x = torch.arange(1,19).reshape(2,3,3)
x

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [6]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [21]:
x[:][1][:]

tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])

In [24]:
x[:][1][1][:]

tensor([13, 14, 15])

In [30]:
x[1][:][1][:][1]

tensor(14)

In [31]:
x[:,1,:]

tensor([[ 4,  5,  6],
        [13, 14, 15]])

In [32]:
x[1,:,1]

tensor([11, 14, 17])

In [33]:
x[1, 1:, 1:]

tensor([[14, 15],
        [17, 18]])

In [34]:
x[0, 1:, :]

tensor([[4, 5, 6],
        [7, 8, 9]])

# Pytorch Tensor and Numpy
* we can convert tensor to numpy: torch.Tensor.numpy()
* to create tensor from numpy array: torch.from_numpy()

In [36]:
# Numpy array to tensor
import numpy as np
array = np.arange(10,20)
array, array.dtype

(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]), dtype('int64'))

In [37]:
tensor = torch.from_numpy(array)
tensor, tensor.dtype # same as numpy dtype the changes does not affects other objects

(tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]), torch.int64)

In [39]:
# Tensor to numpy array
x = torch.rand(3,3)
x, x.dtype

(tensor([[0.6323, 0.0199, 0.3028],
         [0.5220, 0.1634, 0.3790],
         [0.7258, 0.2573, 0.7727]]),
 torch.float32)

In [40]:
arr_from_tensor = x.numpy()
arr_from_tensor, arr_from_tensor.dtype

(array([[0.6323389 , 0.01990068, 0.30283797],
        [0.52203214, 0.16343057, 0.37898886],
        [0.72576463, 0.25733978, 0.7726873 ]], dtype=float32),
 dtype('float32'))